### ISSUE TITLE
Install Issue

### ISSUE THREAD

**Issue by Beezwaad** [dubocr/homebridge-sun-protect#2]
Running latest Homebridge 1.3.1 on latest Raspbian.  Installed via HB UI.  Get error upon HB launch.  Tried reinstalling from terminal.  Tried adding altitudeMax in case needed (not in the examples). 

HOMEBRIDGE RESTART
------------------------
[01/03/2021, 13:40:31] ERROR LOADING PLUGIN homebridge-sun-protect:
[01/03/2021, 13:40:32] TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-sun-protect/src/accessory.ts:171:38)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Plugin.load (/usr/local/lib/node_modules/homebridge/src/plugin.ts:187:27)
    at /usr/local/lib/node_modules/homebridge/src/pluginManager.ts:126:16
    at Map.forEach (<anonymous>)
[

CONFIG
--------
"accessories": [
        {
            "accessory": "SunProtect",
            "name": "Sun",
            "location": {
                "lat":xxx.xxx,
                "long": -xxx.xxx
            },
            "triggers": [
                {
                    "name": "Garden Room",
                    "azimuthMin": 225,
                    "azimuthMax": 285,
                    "altitudeMin": 25
                }
            ]
        }
]

**Comment by dubocr** [comment]
Hi,
Latest release 1.0.4 must fix this issue.
